// GENERATED by server/scripts/sync-stack.mjs from the Stack app source. Do not edit.
import { redesignColors } from './theme.mjs';
import { getMuscleColor, hasMuscleColorPreference, MUSCLE_COLOR_PALETTE, isMuscleColor } from './muscleColors.mjs';
export const DAY_COLORS = MUSCLE_COLOR_PALETTE;
export const isDayColor = isMuscleColor;
export const resolveDayColor = (workout) => {
    const type = workout.exercises[0]?.workoutType;
    if (type && hasMuscleColorPreference(type))
        return getMuscleColor(type);
    if (workout.color && isDayColor(workout.color))
        return DAY_COLORS[workout.color].value;
    return type ? getMuscleColor(type) : redesignColors.ash;
};
