// GENERATED by server/scripts/sync-stack.mjs from the Stack app source. Do not edit.
/**
 * Resolves the exercise names a person typed ("incl db", "lat pulldwn") to
 * Stack's catalog. The AI never chooses Stack exercises; it only copies the
 * name it read, and this module decides, deterministically, in this order:
 *
 *   1. exact Stack exercise name
 *   2. known alias (Stack templates, exercise info, routine-import shorthand)
 *   3. normalized name (case, punctuation, plurals, db/bb/incl/tri…)
 *   4. a single-typo match that is unambiguous           → matched ("typo")
 *      curated ambiguous shorthand or a looser match      → uncertain
 *   5. nothing credible                                  → unresolved
 *
 * Anything short of step 4's strict typo rule is `uncertain`: a wrong match
 * is worse than asking the person to confirm.
 *
 * Pure: no database, store, router or platform imports.
 */
import { AMBIGUOUS_EXERCISE_NAMES, ROUTINE_IMPORT_ALIASES } from './exerciseAliases.mjs';
// ---------------------------------------------------------------------------
// Normalization
// ---------------------------------------------------------------------------
/** Word-level abbreviations. Phrase shorthand lives in exerciseAliases.ts. */
const TOKEN_EXPANSIONS = {
    db: ['dumbbell'],
    dbs: ['dumbbell'],
    bb: ['barbell'],
    kb: ['kettlebell'],
    incl: ['incline'],
    inc: ['incline'],
    dec: ['decline'],
    ext: ['extension'],
    exts: ['extension'],
    tri: ['tricep'],
    tris: ['tricep'],
    triceps: ['tricep'],
    bi: ['bicep'],
    bis: ['bicep'],
    biceps: ['bicep'],
    oh: ['overhead'],
    ohp: ['overhead', 'press'],
    dl: ['deadlift'],
    dls: ['deadlift'],
    rdl: ['romanian', 'deadlift'],
    rdls: ['romanian', 'deadlift'],
    bss: ['bulgarian', 'split', 'squat'],
    cgbp: ['close', 'grip', 'bench', 'press'],
    flys: ['fly'],
    flies: ['fly'],
    flyes: ['fly'],
    pressdown: ['pushdown'],
    pressdowns: ['pushdown'],
};
// 'pres' is a common typo that plain singularization would turn into 'pre'.
const IRREGULAR_SINGULARS = { calves: 'calf', ups: 'up', pres: 'press' };
const singular = (token) => {
    const irregular = IRREGULAR_SINGULARS[token];
    if (irregular)
        return irregular;
    if (token.length <= 3 || /(ss|us|is)$/.test(token))
        return token;
    if (token.endsWith('ies'))
        return `${token.slice(0, -3)}y`;
    if (/(ch|sh|x|ss)es$/.test(token))
        return token.slice(0, -2);
    return token.endsWith('s') ? token.slice(0, -1) : token;
};
/**
 * Comparison tokens for an exercise name. "Single-Arm DB Rows" →
 * [single, arm, dumbbell, row]. Never shown to anyone.
 */
export const looseExerciseTokens = (name) => {
    const words = name
        .normalize('NFKC')
        .toLowerCase()
        .replace(/['’`]/g, '')
        .replace(/[^a-z0-9]+/g, ' ')
        .trim()
        .split(' ')
        .filter(Boolean);
    const tokens = [];
    words.forEach((word, index) => {
        const next = words[index + 1];
        if ((word === 'one' || word === '1') && (next === 'arm' || next === 'leg')) {
            tokens.push('single');
            return;
        }
        for (const expanded of TOKEN_EXPANSIONS[word] ?? [word])
            tokens.push(singular(expanded));
    });
    return tokens;
};
/**
 * Spacing-insensitive key: "pull down", "pull-down" and "pulldowns" share
 * "pulldown"; "Lat Raises" and "lat raise" share "latraise".
 */
export const looseExerciseKey = (name) => looseExerciseTokens(name).join('');
/** Optimal string alignment distance (Damerau–Levenshtein with adjacent swaps). */
export const editDistance = (a, b) => {
    if (a === b)
        return 0;
    const rows = a.length + 1;
    const cols = b.length + 1;
    const d = Array.from({ length: rows }, (_, i) => {
        const row = new Array(cols).fill(0);
        row[0] = i;
        return row;
    });
    for (let j = 0; j < cols; j += 1)
        d[0][j] = j;
    for (let i = 1; i < rows; i += 1) {
        for (let j = 1; j < cols; j += 1) {
            const cost = a[i - 1] === b[j - 1] ? 0 : 1;
            d[i][j] = Math.min(d[i - 1][j] + 1, d[i][j - 1] + 1, d[i - 1][j - 1] + cost);
            if (i > 1 && j > 1 && a[i - 1] === b[j - 2] && a[i - 2] === b[j - 1]) {
                d[i][j] = Math.min(d[i][j], d[i - 2][j - 2] + 1);
            }
        }
    }
    return d[a.length][b.length];
};
/** Words too common to identify a movement on their own. */
const GENERIC_TOKENS = new Set([
    'press', 'curl', 'row', 'raise', 'fly', 'extension', 'machine', 'cable', 'dumbbell',
    'barbell', 'kettlebell', 'single', 'arm', 'grip', 'bar',
]);
const MAX_ALTERNATIVES = 4;
/** More candidates than this means the name is too vague to suggest anything. */
const MAX_LIKELY_CANDIDATES = 8;
const allowedTypos = (length) => (length >= 6 ? 2 : length >= 4 ? 1 : 0);
export const createExerciseResolver = (catalog) => {
    const byName = new Map(catalog.exercises.map((exercise) => [exercise.name, exercise]));
    const nameByKey = new Map();
    for (const exercise of catalog.exercises) {
        const key = looseExerciseKey(exercise.name);
        // Two catalog names with one key can't be told apart: never auto-match it.
        if (nameByKey.has(key) && nameByKey.get(key) !== exercise.name)
            nameByKey.set(key, '');
        else
            nameByKey.set(key, exercise.name);
    }
    const ambiguousByKey = new Map();
    for (const entry of AMBIGUOUS_EXERCISE_NAMES) {
        const key = looseExerciseKey(entry.name);
        if (nameByKey.has(key))
            continue;
        ambiguousByKey.set(key, {
            suggested: entry.suggested && byName.has(entry.suggested) ? entry.suggested : null,
            alternatives: entry.alternatives.filter((name) => byName.has(name)),
        });
    }
    const aliasByKey = new Map();
    const aliases = [
        ...catalog.aliases,
        ...ROUTINE_IMPORT_ALIASES.map(([alias, name]) => ({ alias, name })),
    ];
    for (const { alias, name } of aliases) {
        const key = looseExerciseKey(alias);
        if (!key || !byName.has(name) || nameByKey.has(key) || ambiguousByKey.has(key))
            continue;
        // Conflicting aliases cancel out rather than letting list order decide.
        if (aliasByKey.has(key) && aliasByKey.get(key) !== name)
            aliasByKey.set(key, '');
        else
            aliasByKey.set(key, name);
    }
    const index = [];
    for (const exercise of catalog.exercises)
        index.push({ tokens: looseExerciseTokens(exercise.name), target: exercise.name });
    for (const { alias, name } of aliases) {
        const key = looseExerciseKey(alias);
        if (aliasByKey.get(key) === name)
            index.push({ tokens: looseExerciseTokens(alias), target: name });
    }
    const matched = (method, name) => ({ status: 'matched', method, name, suggestedMatch: null, alternatives: [] });
    const unresolved = { status: 'unresolved', method: null, name: null, suggestedMatch: null, alternatives: [] };
    /** Per-token distance when the token counts match, else Infinity. */
    const tokenDistance = (input, entry, strict) => {
        if (input.length !== entry.length)
            return Infinity;
        let total = 0;
        let differing = 0;
        for (let i = 0; i < input.length; i += 1) {
            const a = input[i];
            const b = entry[i];
            if (a === b)
                continue;
            differing += 1;
            // Changing a word's first letter usually makes a different word (hack/back).
            if (a[0] !== b[0])
                return Infinity;
            const limit = strict ? (Math.min(a.length, b.length) >= 4 ? 1 : 0) : allowedTypos(Math.min(a.length, b.length));
            const distance = editDistance(a, b);
            if (distance > limit)
                return Infinity;
            total += distance;
        }
        if (strict && differing !== 1)
            return Infinity;
        return total;
    };
    const typoMatch = (tokens) => {
        const targets = new Set(index.filter((entry) => tokenDistance(tokens, entry.tokens, true) === 1).map((entry) => entry.target));
        if (targets.size !== 1)
            return null;
        const [target] = targets;
        // No different exercise may be nearly as close.
        const rival = index.some((entry) => entry.target !== target && tokenDistance(tokens, entry.tokens, false) <= 2);
        return rival ? null : target;
    };
    /** Whether two tokens are the same word, allowing a typo or two. */
    const sameWord = (a, b) => {
        if (a === b)
            return true;
        const length = Math.min(a.length, b.length);
        return a[0] === b[0] && length >= 4 && editDistance(a, b) <= (length >= 9 ? 2 : 1);
    };
    /** Input words appear in the entry in the same order ("low to high"). */
    const inOrder = (input, entry) => {
        let position = 0;
        for (const token of entry)
            if (position < input.length && sameWord(input[position], token))
                position += 1;
        return position === input.length;
    };
    const likelyMatches = (tokens) => {
        const input = [...new Set(tokens)];
        const distinctive = input.some((token) => !GENERIC_TOKENS.has(token));
        const scores = new Map();
        for (const entry of index) {
            const entryTokens = [...new Set(entry.tokens)];
            const shared = input.filter((token) => entryTokens.some((other) => sameWord(token, other)));
            const covered = entryTokens.filter((token) => input.some((other) => sameWord(token, other)));
            const sharedDistinctive = shared.some((token) => !GENERIC_TOKENS.has(token));
            const order = inOrder(input, entryTokens) || inOrder(entryTokens, input) ? 2 : 0;
            let score = 0;
            const distance = tokenDistance(tokens, entry.tokens, false);
            if (distance <= 3)
                score = 100 - distance * 10;
            else if (distinctive && shared.length === input.length)
                score = 70 - 5 * (entryTokens.length - covered.length) + order;
            else if (sharedDistinctive && covered.length === entryTokens.length)
                score = 60 - 5 * (input.length - shared.length) + order;
            else if (sharedDistinctive && shared.length >= 2 && shared.length / input.length >= 0.6)
                score = 40 + 5 * shared.length;
            if (score > (scores.get(entry.target) ?? 0))
                scores.set(entry.target, score);
        }
        return [...scores]
            .map(([name, score]) => ({ name, score }))
            .sort((a, b) => b.score - a.score || a.name.length - b.name.length || a.name.localeCompare(b.name));
    };
    const resolve = (rawName) => {
        const trimmed = rawName.trim();
        if (byName.has(trimmed))
            return matched('exact', trimmed);
        const key = looseExerciseKey(trimmed);
        if (!key)
            return unresolved;
        const alias = aliasByKey.get(key);
        if (alias)
            return matched('alias', alias);
        const normalized = nameByKey.get(key);
        if (normalized)
            return matched('normalized', normalized);
        const ambiguous = ambiguousByKey.get(key);
        if (ambiguous) {
            return {
                status: 'uncertain',
                method: 'ambiguous',
                name: null,
                suggestedMatch: ambiguous.suggested,
                alternatives: ambiguous.alternatives.filter((name) => name !== ambiguous.suggested).slice(0, MAX_ALTERNATIVES),
            };
        }
        const tokens = looseExerciseTokens(trimmed);
        const typo = typoMatch(tokens);
        if (typo)
            return matched('typo', typo);
        const likely = likelyMatches(tokens);
        if (likely.length === 0 || likely.length > MAX_LIKELY_CANDIDATES)
            return unresolved;
        // One word ("chest", "lat") names a muscle or family, never one exercise.
        const clearWinner = likely.length === 1 || likely[0].score > likely[1].score;
        const suggestedMatch = clearWinner && new Set(tokens).size > 1 ? likely[0].name : null;
        return {
            status: 'uncertain',
            method: 'likely',
            name: null,
            suggestedMatch,
            alternatives: likely.map((match) => match.name).filter((name) => name !== suggestedMatch).slice(0, MAX_ALTERNATIVES),
        };
    };
    return { resolve, exercise: (name) => byName.get(name) };
};
