// GENERATED by server/scripts/sync-stack.mjs from the Stack app source. Do not edit.
import { splitColors, workoutLoggingColors } from './theme.mjs';
export const MUSCLE_COLOR_PALETTE = {
    orange: { name: 'Orange', value: splitColors.chest },
    blue: { name: 'Blue', value: splitColors.back },
    purple: { name: 'Purple', value: splitColors.shoulders },
    teal: { name: 'Teal', value: splitColors.arms },
    lime: { name: 'Lime', value: splitColors.legs },
    pink: { name: 'Pink', value: splitColors.core },
};
export const isMuscleColor = (value) => typeof value === 'string' && Object.prototype.hasOwnProperty.call(MUSCLE_COLOR_PALETTE, value);
// Pure readers let catalog metadata, reports, and Build use the same preference
// without importing a React hook or a native storage dependency.
let preferences = {};
export function applyMuscleColorPreferences(next) {
    preferences = next;
}
export function getMuscleColorPreferences() {
    return preferences;
}
export function hasMuscleColorPreference(type) {
    return Object.prototype.hasOwnProperty.call(preferences, type);
}
export function getMuscleColor(type) {
    const choice = preferences[type];
    return choice ? MUSCLE_COLOR_PALETTE[choice].value : splitColors[type];
}
export function getWorkoutLoggingColor(type) {
    return hasMuscleColorPreference(type) ? getMuscleColor(type) : workoutLoggingColors[type];
}
