// GENERATED by server/scripts/sync-stack.mjs from the Stack app source. Do not edit.
/**
 * Formats for "Paste my routine".
 *
 *   pasted text ──AI──▶ ParsedRoutine (what the person wrote, validated here)
 *               ──routineImportResult.ts──▶ RoutineImportResult (Stack-owned)
 *               ──toPortableSplit──▶ PortableSplit ──importPortableSplitSync──▶ SQLite
 *
 * The model's JSON is untrusted. `readParsedRoutine` accepts only the exact
 * shape below, sanitizes every string the way the split protocol would, and
 * drops (with a warning) any number outside a plausible range, so nothing
 * malformed reaches resolution. It never throws.
 *
 * Pure: no database, store, router or platform imports.
 */
import { SHARED_SPLIT_LIMITS } from './splitProtocol.mjs';
export const ROUTINE_IMPORT_TYPE = 'stack.routineImport';
export const ROUTINE_IMPORT_VERSION = 1;
export const ROUTINE_IMPORT_LIMITS = Object.freeze({
    /** Pasted text, in UTF-16 units. A dense 7-day routine is ~2,500. */
    maxTextLength: 10_000,
    /** Sanity caps on model output; the split protocol's tighter caps apply at import. */
    maxWorkouts: 30,
    maxExercisesPerWorkout: 60,
    maxTotalExercises: 300,
    maxNotesPerItem: 10,
    maxNoteLength: 200,
    maxUnsupported: 50,
    maxSets: 20,
    maxReps: 100,
    maxDurationSeconds: 2 * 60 * 60,
    routineNameMaxLength: SHARED_SPLIT_LIMITS.splitNameMaxLength,
    workoutNameMaxLength: SHARED_SPLIT_LIMITS.workoutNameMaxLength,
    exerciseNameMaxLength: SHARED_SPLIT_LIMITS.exerciseNameMaxLength,
    groupMaxLength: 32,
});
class InvalidModelOutput extends Error {
    path;
    constructor(message, path) {
        super(message);
        this.path = path;
    }
}
const invalid = (message, path) => {
    throw new InvalidModelOutput(message, path);
};
/** The split protocol's forbidden set: C0/C1 controls, bidi overrides/isolates, ZWSP, BOM. */
const FORBIDDEN_CHARACTERS = /[\u0000-\u001F\u007F-\u009F​‪-‮⁦-⁩﻿]/g;
const LONE_SURROGATES = /[\uD800-\uDBFF](?![\uDC00-\uDFFF])|(?<![\uD800-\uDBFF])[\uDC00-\uDFFF]/g;
/** Same character rules as split names, so a sanitized name always validates. */
export const sanitizeImportText = (value) => value.replace(FORBIDDEN_CHARACTERS, ' ').replace(LONE_SURROGATES, '').replace(/\s+/g, ' ').trim();
const truncate = (text, limit) => {
    if (text.length <= limit)
        return text;
    let cut = text.slice(0, limit).trimEnd();
    if (/[\uD800-\uDBFF]$/.test(cut))
        cut = cut.slice(0, -1);
    return cut;
};
const isRecord = (value) => typeof value === 'object' && value !== null && !Array.isArray(value);
const own = (record, key) => Object.prototype.hasOwnProperty.call(record, key) ? record[key] : undefined;
export const readParsedRoutine = (value) => {
    const warnings = [];
    const warn = (code, message, path) => warnings.push({ code, message, path });
    const text = (input, path, limit, required) => {
        if (input === undefined || input === null) {
            return required ? invalid(`${path} is required.`, path) : null;
        }
        if (typeof input !== 'string')
            return invalid(`${path} must be a string.`, path);
        const clean = sanitizeImportText(input);
        if (clean.length === 0)
            return required ? invalid(`${path} cannot be empty.`, path) : null;
        if (clean.length > limit)
            warn('text_truncated', `${path} was shortened to ${limit} characters.`, path);
        return truncate(clean, limit);
    };
    const list = (input, path) => {
        if (input === undefined || input === null)
            return [];
        if (!Array.isArray(input))
            return invalid(`${path} must be a list.`, path);
        return input;
    };
    const notes = (input, path) => {
        const values = list(input, path);
        const out = [];
        values.forEach((note, index) => {
            const clean = text(note, `${path}[${index}]`, ROUTINE_IMPORT_LIMITS.maxNoteLength, false);
            if (clean)
                out.push(clean);
        });
        if (out.length > ROUTINE_IMPORT_LIMITS.maxNotesPerItem) {
            warn('notes_truncated', `Only the first ${ROUTINE_IMPORT_LIMITS.maxNotesPerItem} notes were kept.`, path);
        }
        return out.slice(0, ROUTINE_IMPORT_LIMITS.maxNotesPerItem);
    };
    /** A wrong type is malformed output; an implausible value is dropped. */
    const count = (input, path, max) => {
        if (input === undefined || input === null)
            return null;
        if (typeof input !== 'number' || !Number.isFinite(input))
            return invalid(`${path} must be a number.`, path);
        if (!Number.isInteger(input) || input < 1 || input > max) {
            warn('value_dropped', `${path} (${input}) is not a whole number from 1 to ${max} and was ignored.`, path);
            return null;
        }
        return input;
    };
    const exercise = (input, path) => {
        if (!isRecord(input))
            return invalid(`${path} must be an object.`, path);
        const rawName = text(own(input, 'rawName'), `${path}.rawName`, ROUTINE_IMPORT_LIMITS.exerciseNameMaxLength, true);
        const perSetValues = list(own(input, 'repsPerSet'), `${path}.repsPerSet`);
        const perSet = perSetValues.map((reps, index) => count(reps, `${path}.repsPerSet[${index}]`, ROUTINE_IMPORT_LIMITS.maxReps));
        let repsPerSet = null;
        if (perSet.length > ROUTINE_IMPORT_LIMITS.maxSets || perSet.some((reps) => reps === null)) {
            warn('value_dropped', `${path}.repsPerSet was not usable and was ignored.`, `${path}.repsPerSet`);
        }
        else if (perSet.length > 0) {
            repsPerSet = perSet;
        }
        return {
            rawName,
            sets: count(own(input, 'sets'), `${path}.sets`, ROUTINE_IMPORT_LIMITS.maxSets),
            reps: count(own(input, 'reps'), `${path}.reps`, ROUTINE_IMPORT_LIMITS.maxReps),
            repsPerSet,
            repsMin: count(own(input, 'repsMin'), `${path}.repsMin`, ROUTINE_IMPORT_LIMITS.maxReps),
            repsMax: count(own(input, 'repsMax'), `${path}.repsMax`, ROUTINE_IMPORT_LIMITS.maxReps),
            durationSeconds: count(own(input, 'durationSeconds'), `${path}.durationSeconds`, ROUTINE_IMPORT_LIMITS.maxDurationSeconds),
            notes: notes(own(input, 'notes'), `${path}.notes`),
            group: text(own(input, 'group'), `${path}.group`, ROUTINE_IMPORT_LIMITS.groupMaxLength, false),
        };
    };
    try {
        if (!isRecord(value))
            invalid('The model response must be a JSON object.', 'root');
        const root = value;
        if (!Array.isArray(own(root, 'workouts')))
            invalid('workouts must be a list.', 'workouts');
        const workoutValues = own(root, 'workouts');
        if (workoutValues.length > ROUTINE_IMPORT_LIMITS.maxWorkouts) {
            invalid(`At most ${ROUTINE_IMPORT_LIMITS.maxWorkouts} workouts are supported.`, 'workouts');
        }
        let total = 0;
        const workouts = workoutValues.map((workoutValue, workoutIndex) => {
            const path = `workouts[${workoutIndex}]`;
            if (!isRecord(workoutValue))
                return invalid(`${path} must be an object.`, path);
            const exerciseValues = list(own(workoutValue, 'exercises'), `${path}.exercises`);
            total += exerciseValues.length;
            if (exerciseValues.length > ROUTINE_IMPORT_LIMITS.maxExercisesPerWorkout || total > ROUTINE_IMPORT_LIMITS.maxTotalExercises) {
                invalid('The routine has more exercises than Stack can import.', `${path}.exercises`);
            }
            return {
                name: text(own(workoutValue, 'name'), `${path}.name`, ROUTINE_IMPORT_LIMITS.workoutNameMaxLength, false),
                notes: notes(own(workoutValue, 'notes'), `${path}.notes`),
                exercises: exerciseValues.map((item, index) => exercise(item, `${path}.exercises[${index}]`)),
            };
        });
        const unsupportedValues = list(own(root, 'unsupported'), 'unsupported').slice(0, ROUTINE_IMPORT_LIMITS.maxUnsupported);
        const unsupported = [];
        unsupportedValues.forEach((item, index) => {
            const path = `unsupported[${index}]`;
            if (!isRecord(item))
                invalid(`${path} must be an object.`, path);
            const record = item;
            const itemText = text(own(record, 'text'), `${path}.text`, ROUTINE_IMPORT_LIMITS.maxNoteLength, false);
            if (!itemText)
                return;
            unsupported.push({
                text: itemText,
                reason: text(own(record, 'reason'), `${path}.reason`, ROUTINE_IMPORT_LIMITS.maxNoteLength, false) ?? 'Not supported by Stack yet.',
            });
        });
        return {
            ok: true,
            value: {
                routineName: text(own(root, 'routineName'), 'routineName', ROUTINE_IMPORT_LIMITS.routineNameMaxLength, false),
                workouts,
                notes: notes(own(root, 'notes'), 'notes'),
                unsupported,
            },
            warnings,
        };
    }
    catch (error) {
        if (error instanceof InvalidModelOutput) {
            return { ok: false, error: { code: 'invalid_model_output', message: error.message, path: error.path } };
        }
        // Hostile getters or anything unexpected still fail closed.
        return { ok: false, error: { code: 'invalid_model_output', message: 'The model response could not be read.' } };
    }
};
