// GENERATED by server/scripts/sync-stack.mjs from the Stack app source. Do not edit.
import { isDayColor } from './colors.mjs';
export const SHARED_SPLIT_TYPE = 'stack.split';
export const SHARED_SPLIT_VERSION = 1;
export const SUPPORTED_SHARED_SPLIT_VERSIONS = [1];
export const PORTABLE_WORKOUT_TYPES = [
    'chest',
    'back',
    'shoulders',
    'arms',
    'legs',
    'core',
];
export const PORTABLE_LOAD_TYPES = [
    'external_weight',
    'bodyweight',
];
export const PORTABLE_METRICS = ['reps', 'duration'];
/** The equipment choices offered by the custom exercise sheet. Built-in
 * seeds carry no equipment, so `null` is also valid. */
export const PORTABLE_EQUIPMENT = ['Barbell', 'Dumbbell', 'Cable', 'Machine'];
const workoutTypesMatch = true;
const loadTypesMatch = true;
const metricsMatch = true;
void workoutTypesMatch;
void loadTypesMatch;
void metricsMatch;
/**
 * Explicit robustness limits. Lengths are UTF-16 code units, the same unit
 * React Native's TextInput `maxLength` counts. Each sits above the matching
 * in-app input limit so no split a user can build today is rejected.
 */
export const SHARED_SPLIT_LIMITS = Object.freeze({
    /** Split name input is maxLength 48. */
    splitNameMaxLength: 64,
    /** Workout name input is maxLength 48. Empty is allowed (derived name). */
    workoutNameMaxLength: 64,
    /** Custom exercise and rename inputs are maxLength 80. */
    exerciseNameMaxLength: 80,
    /** Custom exercises use muscle-group labels; seeds use e.g. "Quads, Glutes". */
    primaryMuscleMaxLength: 48,
    /** The builder has no cap; two full weeks of distinct days is generous. */
    maxWorkouts: 14,
    /** A workout cannot repeat an exercise; 30 is far above any real session. */
    maxExercisesPerWorkout: 30,
    maxTotalExercises: 200,
    maxCustomExercises: 100,
    /**
     * Canonical JSON bytes (UTF-8). Realistic splits are ~1–3 KB; a 7×12 split
     * of all-custom exercises with 80-character names is ~21 KB.
     */
    maxPayloadBytes: 32 * 1024,
});
class ProtocolError extends Error {
    detail;
    constructor(detail) {
        super(detail.message);
        this.detail = detail;
    }
}
const fail = (code, message, path) => {
    throw new ProtocolError({ code, message, path });
};
const capture = (run) => {
    try {
        return { ok: true, value: run() };
    }
    catch (error) {
        if (error instanceof ProtocolError)
            return { ok: false, error: error.detail };
        // Anything unexpected (e.g. a hostile getter) still fails closed.
        return {
            ok: false,
            error: { code: 'invalid_structure', message: 'The shared split could not be read.' },
        };
    }
};
// ---------------------------------------------------------------------------
// Strings & identity
// ---------------------------------------------------------------------------
/** C0/C1 controls, bidi overrides/isolates, zero-width space, BOM. */
const FORBIDDEN_CHARACTERS = /[\u0000-\u001F\u007F-\u009F​‪-‮⁦-⁩﻿]/;
const hasLoneSurrogate = (value) => {
    for (let index = 0; index < value.length; index += 1) {
        const code = value.charCodeAt(index);
        if (code >= 0xd800 && code <= 0xdbff) {
            const next = value.charCodeAt(index + 1);
            if (!(next >= 0xdc00 && next <= 0xdfff))
                return true;
            index += 1;
        }
        else if (code >= 0xdc00 && code <= 0xdfff) {
            return true;
        }
    }
    return false;
};
const readName = (value, path, maxLength, allowEmpty = false) => {
    if (typeof value !== 'string')
        fail('invalid_string', `${path} must be a string.`, path);
    const text = value.trim();
    if (!allowEmpty && text.length === 0)
        fail('empty_name', `${path} cannot be empty.`, path);
    if (text.length > maxLength) {
        fail('string_too_long', `${path} is longer than ${maxLength} characters.`, path);
    }
    if (FORBIDDEN_CHARACTERS.test(text) || hasLoneSurrogate(text)) {
        fail('invalid_string', `${path} contains characters that are not allowed.`, path);
    }
    return text;
};
const readEnum = (value, allowed, path) => {
    if (typeof value !== 'string' || !allowed.includes(value)) {
        fail('unknown_enum_value', `${path} must be one of: ${allowed.join(', ')}.`, path);
    }
    return value;
};
/**
 * Deterministic comparison key for exercise names. Display names are never
 * rewritten; this key only decides whether two names mean the same exercise.
 * "Lat Pulldown", "lat  pulldown" and "LAT PULLDOWN" share one key.
 *
 * NFKC folds compatibility forms (full-width letters, ligatures); whitespace
 * runs collapse; `toLowerCase` is locale-independent so every device agrees.
 * Note this is broader than SQLite's ASCII-only `COLLATE NOCASE`.
 */
export const exerciseMatchKey = (name) => name.normalize('NFKC').trim().replace(/\s+/g, ' ').toLowerCase();
// ---------------------------------------------------------------------------
// Untrusted-object helpers
// ---------------------------------------------------------------------------
const isPlainObject = (value) => typeof value === 'object' && value !== null && !Array.isArray(value);
const own = (record, key) => Object.prototype.hasOwnProperty.call(record, key) ? record[key] : undefined;
const readObject = (value, path) => {
    if (!isPlainObject(value))
        fail('invalid_structure', `${path} must be an object.`, path);
    return value;
};
const readArray = (value, path) => {
    if (!Array.isArray(value))
        fail('invalid_structure', `${path} must be a list.`, path);
    return value;
};
// ---------------------------------------------------------------------------
// Domain validation (shared by serializer and parser)
// ---------------------------------------------------------------------------
const normalizeCustomFields = (record, path) => {
    const equipment = own(record, 'equipment');
    return {
        workoutType: readEnum(own(record, 'workoutType'), PORTABLE_WORKOUT_TYPES, `${path}.workoutType`),
        primaryMuscle: readName(own(record, 'primaryMuscle'), `${path}.primaryMuscle`, SHARED_SPLIT_LIMITS.primaryMuscleMaxLength),
        equipment: equipment === null || equipment === undefined
            ? null
            : readEnum(equipment, PORTABLE_EQUIPMENT, `${path}.equipment`),
        loadType: readEnum(own(record, 'loadType'), PORTABLE_LOAD_TYPES, `${path}.loadType`),
        metric: own(record, 'metric') === undefined
            ? 'reps'
            : readEnum(own(record, 'metric'), PORTABLE_METRICS, `${path}.metric`),
    };
};
const normalizeExercise = (value, path) => {
    const record = readObject(value, path);
    const name = readName(own(record, 'name'), `${path}.name`, SHARED_SPLIT_LIMITS.exerciseNameMaxLength);
    const kind = own(record, 'kind');
    if (kind === 'builtin')
        return { kind, name };
    if (kind === 'custom')
        return { kind, name, ...normalizeCustomFields(record, path) };
    return fail('unknown_enum_value', `${path}.kind must be "builtin" or "custom".`, `${path}.kind`);
};
const sameExerciseIdentity = (a, b) => {
    if (a.kind !== b.kind || a.name !== b.name)
        return false;
    if (a.kind === 'builtin' || b.kind === 'builtin')
        return true;
    return (a.workoutType === b.workoutType &&
        a.primaryMuscle === b.primaryMuscle &&
        a.equipment === b.equipment &&
        a.loadType === b.loadType &&
        a.metric === b.metric);
};
/**
 * Validates an in-memory split and returns a normalised deep copy holding only
 * protocol fields. Rules:
 *  - 1…maxWorkouts workouts, at least one exercise overall (mirrors
 *    `saveCustomSplitDraftSync`); individual workouts may be empty but an
 *    empty workout must be named.
 *  - No exercise twice in one workout (the builder de-duplicates too).
 *  - One match key ↔ one exercise identity across the whole split, so a
 *    payload can never be ambiguous about which exercise a name means.
 */
const normalizeSplit = (input) => {
    const record = readObject(input, 'split');
    const name = readName(own(record, 'name'), 'name', SHARED_SPLIT_LIMITS.splitNameMaxLength);
    const workoutValues = readArray(own(record, 'workouts'), 'workouts');
    if (workoutValues.length === 0)
        fail('no_workouts', 'A split needs at least one workout.', 'workouts');
    if (workoutValues.length > SHARED_SPLIT_LIMITS.maxWorkouts) {
        fail('too_many_workouts', `A split can share at most ${SHARED_SPLIT_LIMITS.maxWorkouts} workouts.`, 'workouts');
    }
    const identities = new Map();
    let total = 0;
    const workouts = workoutValues.map((workoutValue, workoutIndex) => {
        const path = `workouts[${workoutIndex}]`;
        const workout = readObject(workoutValue, path);
        const workoutName = readName(own(workout, 'name'), `${path}.name`, SHARED_SPLIT_LIMITS.workoutNameMaxLength, true);
        const exerciseValues = readArray(own(workout, 'exercises'), `${path}.exercises`);
        if (exerciseValues.length > SHARED_SPLIT_LIMITS.maxExercisesPerWorkout) {
            fail('too_many_exercises', `A workout can share at most ${SHARED_SPLIT_LIMITS.maxExercisesPerWorkout} exercises.`, `${path}.exercises`);
        }
        if (exerciseValues.length === 0 && workoutName.length === 0) {
            fail('empty_workout', 'An empty workout needs a name.', path);
        }
        total += exerciseValues.length;
        if (total > SHARED_SPLIT_LIMITS.maxTotalExercises) {
            fail('too_many_exercises', `A split can share at most ${SHARED_SPLIT_LIMITS.maxTotalExercises} exercises.`, `${path}.exercises`);
        }
        const seen = new Set();
        const exercises = exerciseValues.map((exerciseValue, exerciseIndex) => {
            const exercisePath = `${path}.exercises[${exerciseIndex}]`;
            const exercise = normalizeExercise(exerciseValue, exercisePath);
            const key = exerciseMatchKey(exercise.name);
            if (seen.has(key)) {
                fail('duplicate_exercise', `"${exercise.name}" appears twice in one workout.`, exercisePath);
            }
            seen.add(key);
            const known = identities.get(key);
            if (!known) {
                identities.set(key, exercise);
            }
            else if (!sameExerciseIdentity(known, exercise)) {
                fail(known.kind === 'custom' && exercise.kind === 'custom' && known.name === exercise.name
                    ? 'conflicting_custom_exercise'
                    : 'ambiguous_exercise_name', `"${exercise.name}" refers to two different exercises in this split.`, exercisePath);
            }
            return exercise;
        });
        return { name: workoutName, exercises, ...(isDayColor(own(workout, 'color')) ? { color: own(workout, 'color') } : {}) };
    });
    if (total === 0)
        fail('empty_split', 'A split needs at least one exercise.', 'workouts');
    return { name, workouts };
};
export const validatePortableSplit = (input) => capture(() => normalizeSplit(input));
// ---------------------------------------------------------------------------
// Domain → wire → canonical JSON
// ---------------------------------------------------------------------------
const toWire = (split) => {
    const custom = [];
    const hoisted = new Set();
    const workouts = split.workouts.map((workout) => ({
        name: workout.name,
        ...(workout.color ? { color: workout.color } : {}),
        exercises: workout.exercises.map((exercise) => {
            if (exercise.kind === 'custom' && !hoisted.has(exercise.name)) {
                hoisted.add(exercise.name);
                // Explicit field order keeps the encoding canonical.
                custom.push({
                    name: exercise.name,
                    workoutType: exercise.workoutType,
                    primaryMuscle: exercise.primaryMuscle,
                    equipment: exercise.equipment,
                    loadType: exercise.loadType,
                    ...(exercise.metric === 'duration' ? { metric: 'duration' } : {}),
                });
            }
            return exercise.name;
        }),
    }));
    const wire = {
        type: SHARED_SPLIT_TYPE,
        v: SHARED_SPLIT_VERSION,
        name: split.name,
        workouts,
    };
    if (custom.length > 0)
        wire.custom = custom;
    return wire;
};
export const utf8ByteLength = (text) => {
    let bytes = 0;
    for (let index = 0; index < text.length; index += 1) {
        const code = text.charCodeAt(index);
        if (code < 0x80)
            bytes += 1;
        else if (code < 0x800)
            bytes += 2;
        else if (code >= 0xd800 && code <= 0xdbff) {
            bytes += 4;
            index += 1;
        }
        else
            bytes += 3;
    }
    return bytes;
};
const assertPayloadSize = (json) => {
    // UTF-8 bytes ≥ UTF-16 units, so the cheap length check is a safe pre-filter.
    if (json.length > SHARED_SPLIT_LIMITS.maxPayloadBytes ||
        utf8ByteLength(json) > SHARED_SPLIT_LIMITS.maxPayloadBytes) {
        fail('payload_too_large', `Shared splits are limited to ${SHARED_SPLIT_LIMITS.maxPayloadBytes} bytes.`);
    }
};
/**
 * Validates a portable split and returns its canonical V1 JSON text. Equal
 * normalised input always yields byte-identical output.
 */
export const serializeSharedSplit = (split) => capture(() => {
    const json = JSON.stringify(toWire(normalizeSplit(split)));
    assertPayloadSize(json);
    return json;
});
/** The wire object for a split, e.g. for inspection or alternative encodings. */
export const toSharedSplitWire = (split) => capture(() => toWire(normalizeSplit(split)));
// ---------------------------------------------------------------------------
// Canonical JSON → wire → domain
// ---------------------------------------------------------------------------
/**
 * JSON.parse silently keeps the last of duplicate keys, which would let two
 * readers of one payload disagree. Runs only on text JSON.parse accepted.
 */
const findDuplicateKey = (text) => {
    const stack = [];
    let expectKey = false;
    for (let index = 0; index < text.length; index += 1) {
        const char = text[index];
        if (char === '"') {
            let end = index + 1;
            while (text[end] !== '"')
                end += text[end] === '\\' ? 2 : 1;
            if (expectKey) {
                const keys = stack[stack.length - 1];
                const key = JSON.parse(text.slice(index, end + 1));
                if (keys.has(key))
                    return key;
                keys.add(key);
                expectKey = false;
            }
            index = end;
        }
        else if (char === '{') {
            stack.push(new Set());
            expectKey = true;
        }
        else if (char === '[') {
            stack.push(null);
            expectKey = false;
        }
        else if (char === '}' || char === ']') {
            stack.pop();
            expectKey = false;
        }
        else if (char === ',') {
            expectKey = stack[stack.length - 1] instanceof Set;
        }
    }
    return null;
};
const readVersion = (root) => {
    const type = own(root, 'type');
    if (type !== SHARED_SPLIT_TYPE) {
        fail('unsupported_type', typeof type === 'string'
            ? `"${type.slice(0, 40)}" is not a shared split this version of Stack understands.`
            : 'This is not a shared Stack split.', 'type');
    }
    const version = own(root, 'v');
    if (version === undefined)
        fail('missing_version', 'The shared split has no version.', 'v');
    if (typeof version !== 'number' || !Number.isSafeInteger(version) || version < 1) {
        fail('invalid_version', 'The shared split version is invalid.', 'v');
    }
    if (!SUPPORTED_SHARED_SPLIT_VERSIONS.includes(version)) {
        fail('unsupported_version', version > SHARED_SPLIT_VERSION
            ? 'This split was shared from a newer version of Stack. Update Stack to open it.'
            : 'This shared split version is no longer supported.', 'v');
    }
    return version;
};
/** V1 wire → domain. Unknown fields are ignored so additive changes stay V1. */
const fromWireV1 = (root) => {
    const customValue = own(root, 'custom');
    const customValues = customValue === undefined ? [] : readArray(customValue, 'custom');
    if (customValues.length > SHARED_SPLIT_LIMITS.maxCustomExercises) {
        fail('too_many_exercises', `A split can share at most ${SHARED_SPLIT_LIMITS.maxCustomExercises} custom exercises.`, 'custom');
    }
    const definitions = new Map();
    customValues.forEach((value, index) => {
        const path = `custom[${index}]`;
        const record = readObject(value, path);
        const name = readName(own(record, 'name'), `${path}.name`, SHARED_SPLIT_LIMITS.exerciseNameMaxLength);
        if (own(record, 'equipment') === undefined) {
            fail('invalid_structure', `${path}.equipment is required (use null for none).`, `${path}.equipment`);
        }
        const key = exerciseMatchKey(name);
        if (definitions.has(key)) {
            fail('conflicting_custom_exercise', `"${name}" is defined more than once.`, path);
        }
        definitions.set(key, { kind: 'custom', name, ...normalizeCustomFields(record, path) });
    });
    const referenced = new Set();
    const workoutValues = readArray(own(root, 'workouts'), 'workouts');
    // Bound work before mapping; normalizeSplit repeats the exact checks.
    if (workoutValues.length > SHARED_SPLIT_LIMITS.maxWorkouts) {
        fail('too_many_workouts', `A split can share at most ${SHARED_SPLIT_LIMITS.maxWorkouts} workouts.`, 'workouts');
    }
    const workouts = workoutValues.map((workoutValue, workoutIndex) => {
        const path = `workouts[${workoutIndex}]`;
        const workout = readObject(workoutValue, path);
        const exerciseValues = readArray(own(workout, 'exercises'), `${path}.exercises`);
        if (exerciseValues.length > SHARED_SPLIT_LIMITS.maxExercisesPerWorkout) {
            fail('too_many_exercises', `A workout can share at most ${SHARED_SPLIT_LIMITS.maxExercisesPerWorkout} exercises.`, `${path}.exercises`);
        }
        return {
            name: own(workout, 'name'),
            color: own(workout, 'color'),
            exercises: exerciseValues.map((value, exerciseIndex) => {
                const exercisePath = `${path}.exercises[${exerciseIndex}]`;
                const name = readName(value, exercisePath, SHARED_SPLIT_LIMITS.exerciseNameMaxLength);
                const key = exerciseMatchKey(name);
                const definition = definitions.get(key);
                if (!definition)
                    return { kind: 'builtin', name };
                if (definition.name !== name) {
                    fail('exercise_name_mismatch', `"${name}" does not exactly match its custom definition "${definition.name}".`, exercisePath);
                }
                referenced.add(key);
                return { ...definition };
            }),
        };
    });
    const split = normalizeSplit({ name: own(root, 'name'), workouts });
    for (const [key, definition] of definitions) {
        if (!referenced.has(key)) {
            fail('unreferenced_custom_exercise', `"${definition.name}" is defined but never used.`, 'custom');
        }
    }
    return split;
};
/**
 * Parses canonical (or any equivalent) JSON text into a validated, normalised
 * portable split. Never throws.
 */
export const parseSharedSplitJson = (json) => capture(() => {
    if (typeof json !== 'string')
        fail('invalid_json', 'The shared split must be JSON text.');
    assertPayloadSize(json);
    let root;
    try {
        root = JSON.parse(json);
    }
    catch {
        fail('invalid_json', 'The shared split is not valid JSON.');
    }
    const duplicate = findDuplicateKey(json);
    if (duplicate !== null) {
        fail('duplicate_key', `The field "${duplicate.slice(0, 40)}" appears more than once.`);
    }
    const record = readObject(root, 'payload');
    readVersion(record);
    // Only V1 exists today; future versions dispatch here.
    return fromWireV1(record);
});
