#!/usr/bin/env node
/**
 * Copies Stack's routine-import logic and exercise catalog into the server.
 *
 * The app source is the single source of truth. Railway builds only
 * `server/`, so the pure TypeScript modules are compiled to plain ESM here and
 * the catalog is extracted to JSON. Run after changing any of them:
 *
 *   node server/scripts/sync-stack.mjs          # write
 *   node server/scripts/sync-stack.mjs --check  # exit 1 if out of date
 */
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const serverRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const appRoot = path.resolve(serverRoot, '..');
const outDir = path.join(serverRoot, 'src/stack');
const { extractStackCatalog, loadTypeScript } = require('./stackCatalog.cjs');

/** App modules the server runs, by their `@/` import path. */
const MODULES = [
  'constants/theme',
  'constants/muscleColors',
  'features/custom-split/colors',
  'features/sharing/splitProtocol',
  'features/routineImport/exerciseAliases',
  'features/routineImport/exerciseResolver',
  'features/routineImport/routineImportProtocol',
  'features/routineImport/routineImportResult',
];

const HEADER = '// GENERATED by server/scripts/sync-stack.mjs from the Stack app source. Do not edit.\n';

const build = () => {
  const ts = loadTypeScript(appRoot);
  const files = new Map();
  for (const id of MODULES) {
    const source = fs.readFileSync(path.join(appRoot, `${id}.ts`), 'utf8');
    let js = ts.transpileModule(source, {
      compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022 },
      fileName: `${id}.ts`,
    }).outputText;
    js = js.replace(/from '@\/([^']+)'/g, (_, imported) => {
      if (!MODULES.includes(imported)) throw new Error(`${id} imports @/${imported}, which the server does not bundle.`);
      return `from './${path.basename(imported)}.mjs'`;
    });
    if (/from '(?!\.\/)/.test(js) || /\brequire\(/.test(js)) throw new Error(`${id} has a runtime dependency the server cannot load.`);
    files.set(`${path.basename(id)}.mjs`, HEADER + js);
  }
  files.set('catalog.json', `${JSON.stringify(extractStackCatalog(appRoot), null, 2)}\n`);
  return files;
};

const files = build();
if (process.argv.includes('--check')) {
  const stale = [...files].filter(([name, content]) => {
    const target = path.join(outDir, name);
    return !fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content;
  });
  if (stale.length > 0) {
    console.error(`server/src/stack is out of date (${stale.map(([name]) => name).join(', ')}). Run: node server/scripts/sync-stack.mjs`);
    process.exit(1);
  }
  console.log('server/src/stack is up to date.');
} else {
  fs.mkdirSync(outDir, { recursive: true });
  for (const [name, content] of files) fs.writeFileSync(path.join(outDir, name), content);
  console.log(`Wrote ${files.size} files to server/src/stack.`);
}
